name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Generate wrapper (if missing)
      run: |
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "Gradle wrapper jar missing; bootstrapping wrapper"
          curl -sLo gradle-install.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-install.zip -d /tmp/gradle8
          /tmp/gradle8/gradle-8.7/bin/gradle wrapper --gradle-version 8.7
        fi
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build debug APK
      run: ./gradlew --version && ./gradlew assembleDebug --stacktrace --no-daemon
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mal-downloader-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
